### ISSUE TITLE
ChatGPT bot

### ISSUE THREAD

**Issue by umputun** [radio-t/super-bot#93]
идея в том, чтоб добавить бот который будет через [ChatGPT  API](https://openai.com/blog/introducing-chatgpt-and-whisper-apis) делать полезное

Пока у меня 2 идеи:

- бот время от времени просыпается и пытается что-то сказать. Делать это можно изредка, и, может ограничить только теми сообщениями которые заканчиваются на "?"
- к боту можно обратиться и он может что-то ответить. Непонятно какие тут вводит ограничения, но надо как-то очень аккуратно, чтоб не превратить чат в сплошной разговор с ботом

технически все это выглядит несложно: бот будет помнить последние N сообщенией (конфигурируется) и у нас будет промпт (тоже в конфигурации где-то) что мы ему посылаем плюс эти N сообщений

Прочие идеи тоже приветствуются

**Comment by adfslslddkds** [comment]
Бот может случайным образом реагировал на фиксированный набор фраз. Необязательно на вопрос.  При этом текст в ChatGPT можно посылать не как есть, а с дополнительными заданиями. Например как бы ты ответил на такой комментарий в стихах. Или расскажи истори про... Но тогда надо подумать как скрыть этот набор фраз, чтобы про них все время не писали, хотя можно и не скрывать.

**Comment by umputun** [comment]
>  При этом текст в ChatGPT можно посылать не как есть, а с дополнительными заданиями

это про то, что я назвал "промт в конфигурации". Т.е. у нас будет нечто типа gpt.yml который вполне может бут приватным и там нечто такое:

```yml
 name: "react randomly"
  prompts:
     - "как бы ты ответил в стихах"
     - "продолжи дискуссию в научном стиле"
     - "ответь как гопник"
     
  name: "direct"
   prompts:
     - "ответь по сути, не более 50 слов"
     - "ответь вопросом" 
```

бот будет выбирать один из промпто из подходящей секции рандомно
